global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus self-monitoring

  - job_name: 'your_app'
    static_configs:
      - targets: ['localhost:3000'] # Your application
